#!/usr/bin/env bash

# ╔══════════════════════════════════════════════════════════════╗
# ║  WireGuard VPN Setup for Linux                                ║
# ╚══════════════════════════════════════════════════════════════╝

WG_DIR="/etc/wireguard"
WG_INTERFACE="wg0"
WG_PORT="51820"
VPN_SUBNET="10.200.200"
CLIENT_DIR="$SCRIPT_DIR/vpn/clients"

# Setup WireGuard
setup_wireguard() {
    section "Setting up WireGuard VPN"
    
    # Install WireGuard
    install_wireguard
    
    # Check if already configured
    if [ -f "$WG_DIR/$WG_INTERFACE.conf" ]; then
        warn "WireGuard is already configured"
        if confirm "Reconfigure WireGuard?"; then
            sudo wg-quick down $WG_INTERFACE 2>/dev/null || true
        else
            return 0
        fi
    fi
    
    # Generate server keys
    generate_server_keys
    
    # Create server config
    create_server_config
    
    # Enable IP forwarding
    enable_ip_forwarding
    
    # Start WireGuard
    start_wireguard
    
    # Generate client config
    if confirm "Generate a client configuration?" "y"; then
        generate_client_config
    fi
    
    success "WireGuard VPN setup complete!"
}

# Install WireGuard
install_wireguard() {
    step "Installing WireGuard..."
    
    if command_exists wg; then
        success "WireGuard already installed"
        return 0
    fi
    
    case "$PKG_MANAGER" in
        apt)
            sudo apt install -y wireguard wireguard-tools qrencode
            ;;
        dnf|yum)
            sudo $PKG_MANAGER install -y wireguard-tools qrencode
            ;;
        pacman)
            sudo pacman -S --noconfirm wireguard-tools qrencode
            ;;
    esac
    
    success "WireGuard installed"
}

# Generate server keys
generate_server_keys() {
    step "Generating server keys..."
    
    sudo mkdir -p "$WG_DIR"
    sudo chmod 700 "$WG_DIR"
    
    # Generate private key
    wg genkey | sudo tee "$WG_DIR/server_private.key" > /dev/null
    sudo chmod 600 "$WG_DIR/server_private.key"
    
    # Generate public key
    sudo cat "$WG_DIR/server_private.key" | wg pubkey | sudo tee "$WG_DIR/server_public.key" > /dev/null
    
    success "Server keys generated"
}

# Create server configuration
create_server_config() {
    step "Creating server configuration..."
    
    local server_private_key=$(sudo cat "$WG_DIR/server_private.key")
    local server_ip="${VPN_SUBNET}.1/24"
    
    # Detect default network interface
    local default_interface=$(ip route | grep default | awk '{print $5}' | head -1)
    
    sudo tee "$WG_DIR/$WG_INTERFACE.conf" > /dev/null <<EOF
# WireGuard Server Configuration
# Generated by Home Server Setup

[Interface]
# Server private key
PrivateKey = $server_private_key

# VPN IP address
Address = $server_ip

# Listen port
ListenPort = $WG_PORT

# Save configuration on shutdown
SaveConfig = false

# NAT / Firewall rules
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o $default_interface -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o $default_interface -j MASQUERADE

# Peers will be added below
EOF
    
    sudo chmod 600 "$WG_DIR/$WG_INTERFACE.conf"
    
    success "Server configuration created"
}

# Enable IP forwarding
enable_ip_forwarding() {
    step "Enabling IP forwarding..."
    
    # Enable now
    sudo sysctl -w net.ipv4.ip_forward=1 > /dev/null
    sudo sysctl -w net.ipv6.conf.all.forwarding=1 > /dev/null
    
    # Make permanent
    if ! grep -q "net.ipv4.ip_forward=1" /etc/sysctl.conf; then
        echo "net.ipv4.ip_forward=1" | sudo tee -a /etc/sysctl.conf > /dev/null
    fi
    
    if ! grep -q "net.ipv6.conf.all.forwarding=1" /etc/sysctl.conf; then
        echo "net.ipv6.conf.all.forwarding=1" | sudo tee -a /etc/sysctl.conf > /dev/null
    fi
    
    success "IP forwarding enabled"
}

# Start WireGuard
start_wireguard() {
    step "Starting WireGuard..."
    
    sudo systemctl enable wg-quick@$WG_INTERFACE
    sudo systemctl start wg-quick@$WG_INTERFACE
    
    # Verify
    if systemctl is-active --quiet wg-quick@$WG_INTERFACE; then
        success "WireGuard is running!"
        
        # Show status
        echo ""
        sudo wg show $WG_INTERFACE
        echo ""
    else
        error "Failed to start WireGuard"
        warn "Check logs: journalctl -u wg-quick@$WG_INTERFACE"
    fi
}

# Generate client configuration
generate_client_config() {
    mkdir -p "$CLIENT_DIR"
    
    echo ""
    read -p "$(echo -e ${CYAN}"Enter client name: "${NC})" client_name
    
    if [ -z "$client_name" ]; then
        error "Client name is required"
        return 1
    fi
    
    # Sanitize client name
    client_name=$(echo "$client_name" | tr -cd '[:alnum:]_-')
    
    step "Generating keys for $client_name..."
    
    # Generate client keys
    local client_private_key=$(wg genkey)
    local client_public_key=$(echo "$client_private_key" | wg pubkey)
    
    # Find next available IP
    local client_number=$(sudo grep -c "^\[Peer\]" "$WG_DIR/$WG_INTERFACE.conf" 2>/dev/null || echo "0")
    client_number=$((client_number + 2))  # Start at .2 (server is .1)
    local client_ip="${VPN_SUBNET}.${client_number}/32"
    
    # Get server info
    local server_public_key=$(sudo cat "$WG_DIR/server_public.key")
    local server_endpoint=$(get_public_ip)
    local local_ip=$(get_local_ip)
    
    if [ "$server_endpoint" = "unknown" ]; then
        warn "Could not detect public IP. Using local IP for endpoint."
        server_endpoint="$local_ip"
    fi
    
    # Add peer to server config
    step "Adding peer to server configuration..."
    
    sudo tee -a "$WG_DIR/$WG_INTERFACE.conf" > /dev/null <<EOF

# Client: $client_name
[Peer]
PublicKey = $client_public_key
AllowedIPs = $client_ip
EOF
    
    # Reload WireGuard
    sudo wg syncconf $WG_INTERFACE <(sudo wg-quick strip $WG_INTERFACE)
    
    # Create client config
    local client_config="$CLIENT_DIR/${client_name}.conf"
    
    cat > "$client_config" <<EOF
# WireGuard Client Configuration
# Client: $client_name
# Generated: $(date)

[Interface]
# Client private key
PrivateKey = $client_private_key

# Client VPN IP
Address = $client_ip

# DNS server (use server's DNS or public DNS)
DNS = 1.1.1.1, 8.8.8.8

[Peer]
# Server public key
PublicKey = $server_public_key

# Server endpoint (public IP or domain)
Endpoint = $server_endpoint:$WG_PORT

# Route all traffic through VPN (0.0.0.0/0)
# Or just the home network ($VPN_SUBNET.0/24, ${local_ip%.*}.0/24)
AllowedIPs = $VPN_SUBNET.0/24, ${local_ip%.*}.0/24

# Keep connection alive (important for NAT)
PersistentKeepalive = 25
EOF
    
    success "Client configuration created: $client_config"
    
    # Generate QR code
    if command_exists qrencode; then
        step "Generating QR code..."
        qrencode -t ansiutf8 < "$client_config"
        
        # Save QR code as PNG
        qrencode -o "$CLIENT_DIR/${client_name}_qr.png" < "$client_config"
        info "QR code saved to: $CLIENT_DIR/${client_name}_qr.png"
    fi
    
    echo ""
    echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${BOLD}Client Configuration:${NC}"
    echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    cat "$client_config"
    echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
    
    info "To add this client to another device:"
    info "  1. Install WireGuard app on the device"
    info "  2. Import the config file or scan the QR code"
    info "  3. Connect and you'll be on your home network!"
}

# List clients
list_clients() {
    section "Configured Clients"
    
    if [ -f "$WG_DIR/$WG_INTERFACE.conf" ]; then
        echo ""
        sudo wg show $WG_INTERFACE
        echo ""
    else
        warn "WireGuard is not configured"
    fi
}

# Show VPN status
vpn_status() {
    if command_exists wg; then
        if systemctl is-active --quiet wg-quick@$WG_INTERFACE 2>/dev/null; then
            success "WireGuard is running"
            echo ""
            sudo wg show $WG_INTERFACE
        else
            warn "WireGuard is not running"
        fi
    else
        error "WireGuard is not installed"
    fi
}

# Export functions
export -f setup_wireguard generate_client_config list_clients vpn_status
